#ifndef POKEMON_INDEX_ENG_H
#define POKEMON_INDEX_ENG_H

#include <cstdint>
#include <unordered_map>

namespace PokemonIndex {

// ============================================================================
// Type Codes (Gen 1 & Gen 2)
// ============================================================================

enum Gen1Type : uint8_t {
    TYPE_NORMAL   = 0x00,
    TYPE_FIGHTING = 0x01,
    TYPE_FLYING   = 0x02,
    TYPE_POISON   = 0x03,
    TYPE_GROUND   = 0x04,
    TYPE_ROCK     = 0x05,
    TYPE_BIRD     = 0x06, // Unused type seen on MissingNo.
    TYPE_BUG      = 0x07,
    TYPE_GHOST    = 0x08,
    TYPE_STEEL    = 0x09, // Gen 2
    TYPE_FIRE     = 0x14,
    TYPE_WATER    = 0x15,
    TYPE_GRASS    = 0x16,
    TYPE_ELECTRIC = 0x17,
    TYPE_PSYCHIC  = 0x18,
    TYPE_ICE      = 0x19,
    TYPE_DRAGON   = 0x1A,
    TYPE_DARK     = 0x1B, // Gen 2
    TYPE_CURSE    = 0x13, // ??? type (used by moves like Curse)
    TYPE_UNKNOWN  = 0xFF
};

// ============================================================================
// Type Codes (Gen 3)  (different numbering than Gen 1/2)
// ============================================================================

enum Gen3Type : uint8_t {
    G3_NORMAL   = 0x00,
    G3_FIGHTING = 0x01,
    G3_FLYING   = 0x02,
    G3_POISON   = 0x03,
    G3_GROUND   = 0x04,
    G3_ROCK     = 0x05,
    G3_BUG      = 0x06,
    G3_GHOST    = 0x07,
    G3_STEEL    = 0x08,
    G3_MYSTERY  = 0x09,   // "???"
    G3_FIRE     = 0x0A,
    G3_WATER    = 0x0B,
    G3_GRASS    = 0x0C,
    G3_ELECTRIC = 0x0D,
    G3_PSYCHIC  = 0x0E,
    G3_ICE      = 0x0F,
    G3_DRAGON   = 0x10,
    G3_DARK     = 0x11,

    G3_UNKNOWN  = 0xFF
};

// ============================================================================
// Pokémon Data Structure (Gen 1/2/3)
// ============================================================================

struct PokemonInfo {
    const char* name;
    uint8_t type1;
    uint8_t type2;
    uint16_t nationalDexNum;
};

// ============================================================================
// Generation 1 Pokémon Table
// ============================================================================

static const std::unordered_map<uint8_t, PokemonInfo> GEN1_POKEMON = {
    {0x01, {"Rhydon", TYPE_GROUND, TYPE_ROCK, 112}},
    {0x02, {"Kangaskhan", TYPE_NORMAL, TYPE_NORMAL, 115}},
    {0x03, {"Nidoran♂", TYPE_POISON, TYPE_POISON, 32}},
    {0x04, {"Clefairy", TYPE_NORMAL, TYPE_NORMAL, 35}},
    {0x05, {"Spearow", TYPE_NORMAL, TYPE_FLYING, 21}},
    {0x06, {"Voltorb", TYPE_ELECTRIC, TYPE_ELECTRIC, 100}},
    {0x07, {"Nidoking", TYPE_POISON, TYPE_GROUND, 34}},
    {0x08, {"Slowbro", TYPE_WATER, TYPE_PSYCHIC, 80}},
    {0x09, {"Ivysaur", TYPE_GRASS, TYPE_POISON, 2}},
    {0x0A, {"Exeggutor", TYPE_GRASS, TYPE_PSYCHIC, 103}},
    {0x0B, {"Lickitung", TYPE_NORMAL, TYPE_NORMAL, 108}},
    {0x0C, {"Exeggcute", TYPE_GRASS, TYPE_PSYCHIC, 102}},
    {0x0D, {"Grimer", TYPE_POISON, TYPE_POISON, 88}},
    {0x0E, {"Gengar", TYPE_GHOST, TYPE_POISON, 94}},
    {0x0F, {"Nidoran♀", TYPE_POISON, TYPE_POISON, 29}},
    {0x10, {"Nidoqueen", TYPE_POISON, TYPE_GROUND, 31}},
    {0x11, {"Cubone", TYPE_GROUND, TYPE_GROUND, 104}},
    {0x12, {"Rhyhorn", TYPE_GROUND, TYPE_ROCK, 111}},
    {0x13, {"Lapras", TYPE_WATER, TYPE_ICE, 131}},
    {0x14, {"Arcanine", TYPE_FIRE, TYPE_FIRE, 59}},
    {0x15, {"Mew", TYPE_PSYCHIC, TYPE_PSYCHIC, 151}},
    {0x16, {"Gyarados", TYPE_WATER, TYPE_FLYING, 130}},
    {0x17, {"Shellder", TYPE_WATER, TYPE_WATER, 90}},
    {0x18, {"Tentacool", TYPE_WATER, TYPE_POISON, 72}},
    {0x19, {"Gastly", TYPE_GHOST, TYPE_POISON, 92}},
    {0x1A, {"Scyther", TYPE_BUG, TYPE_FLYING, 123}},
    {0x1B, {"Staryu", TYPE_WATER, TYPE_WATER, 120}},
    {0x1C, {"Blastoise", TYPE_WATER, TYPE_WATER, 9}},
    {0x1D, {"Pinsir", TYPE_BUG, TYPE_BUG, 127}},
    {0x1E, {"Tangela", TYPE_GRASS, TYPE_GRASS, 114}},
    {0x1F, {"MissingNo. (Scizor)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x20, {"MissingNo. (Shuckle)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x21, {"Growlithe", TYPE_FIRE, TYPE_FIRE, 58}},
    {0x22, {"Onix", TYPE_ROCK, TYPE_GROUND, 95}},
    {0x23, {"Fearow", TYPE_NORMAL, TYPE_FLYING, 22}},
    {0x24, {"Pidgey", TYPE_NORMAL, TYPE_FLYING, 16}},
    {0x25, {"Slowpoke", TYPE_WATER, TYPE_PSYCHIC, 79}},
    {0x26, {"Kadabra", TYPE_PSYCHIC, TYPE_PSYCHIC, 64}},
    {0x27, {"Graveler", TYPE_ROCK, TYPE_GROUND, 75}},
    {0x28, {"Chansey", TYPE_NORMAL, TYPE_NORMAL, 113}},
    {0x29, {"Machoke", TYPE_FIGHTING, TYPE_FIGHTING, 67}},
    {0x2A, {"Mr. Mime", TYPE_PSYCHIC, TYPE_PSYCHIC, 122}},
    {0x2B, {"Hitmonlee", TYPE_FIGHTING, TYPE_FIGHTING, 106}},
    {0x2C, {"Hitmonchan", TYPE_FIGHTING, TYPE_FIGHTING, 107}},
    {0x2D, {"Arbok", TYPE_POISON, TYPE_POISON, 24}},
    {0x2E, {"Parasect", TYPE_BUG, TYPE_GRASS, 47}},
    {0x2F, {"Psyduck", TYPE_WATER, TYPE_WATER, 54}},
    {0x30, {"Drowzee", TYPE_PSYCHIC, TYPE_PSYCHIC, 96}},
    {0x31, {"Golem", TYPE_ROCK, TYPE_GROUND, 76}},
    {0x32, {"MissingNo. (Heracross)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x33, {"Magmar", TYPE_FIRE, TYPE_FIRE, 126}},
    {0x34, {"MissingNo. (Ho-Oh)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x35, {"Electabuzz", TYPE_ELECTRIC, TYPE_ELECTRIC, 125}},
    {0x36, {"Magneton", TYPE_ELECTRIC, TYPE_ELECTRIC, 82}},
    {0x37, {"Koffing", TYPE_POISON, TYPE_POISON, 109}},
    {0x38, {"MissingNo. (Sneasel)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x39, {"Mankey", TYPE_FIGHTING, TYPE_FIGHTING, 56}},
    {0x3A, {"Seel", TYPE_WATER, TYPE_WATER, 86}},
    {0x3B, {"Diglett", TYPE_GROUND, TYPE_GROUND, 50}},
    {0x3C, {"Tauros", TYPE_NORMAL, TYPE_NORMAL, 128}},
    {0x3D, {"MissingNo. (Teddiursa)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x3E, {"MissingNo. (Ursaring)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x3F, {"MissingNo. (Slugma)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x40, {"Farfetch'd", TYPE_NORMAL, TYPE_FLYING, 83}},
    {0x41, {"Venonat", TYPE_BUG, TYPE_POISON, 48}},
    {0x42, {"Dragonite", TYPE_DRAGON, TYPE_FLYING, 149}},
    {0x43, {"MissingNo. (Magcargo)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x44, {"MissingNo. (Swinub)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x45, {"MissingNo. (Piloswine)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x46, {"Doduo", TYPE_NORMAL, TYPE_FLYING, 84}},
    {0x47, {"Poliwag", TYPE_WATER, TYPE_WATER, 60}},
    {0x48, {"Jynx", TYPE_ICE, TYPE_PSYCHIC, 124}},
    {0x49, {"Moltres", TYPE_FIRE, TYPE_FLYING, 146}},
    {0x4A, {"Articuno", TYPE_ICE, TYPE_FLYING, 144}},
    {0x4B, {"Zapdos", TYPE_ELECTRIC, TYPE_FLYING, 145}},
    {0x4C, {"Ditto", TYPE_NORMAL, TYPE_NORMAL, 132}},
    {0x4D, {"Meowth", TYPE_NORMAL, TYPE_NORMAL, 52}},
    {0x4E, {"Krabby", TYPE_WATER, TYPE_WATER, 98}},
    {0x4F, {"MissingNo. (Corsola)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x50, {"MissingNo. (Remoraid)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x51, {"MissingNo. (Octillery)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x52, {"Vulpix", TYPE_FIRE, TYPE_FIRE, 37}},
    {0x53, {"Ninetales", TYPE_FIRE, TYPE_FIRE, 38}},
    {0x54, {"Pikachu", TYPE_ELECTRIC, TYPE_ELECTRIC, 25}},
    {0x55, {"Raichu", TYPE_ELECTRIC, TYPE_ELECTRIC, 26}},
    {0x56, {"MissingNo. (Delibird)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x57, {"MissingNo. (Mantine)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x58, {"Dratini", TYPE_DRAGON, TYPE_DRAGON, 147}},
    {0x59, {"Dragonair", TYPE_DRAGON, TYPE_DRAGON, 148}},
    {0x5A, {"Kabuto", TYPE_ROCK, TYPE_WATER, 140}},
    {0x5B, {"Kabutops", TYPE_ROCK, TYPE_WATER, 141}},
    {0x5C, {"Horsea", TYPE_WATER, TYPE_WATER, 116}},
    {0x5D, {"Seadra", TYPE_WATER, TYPE_WATER, 117}},
    {0x5E, {"MissingNo. (Skarmory)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x5F, {"MissingNo. (Houndour)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x60, {"Sandshrew", TYPE_GROUND, TYPE_GROUND, 27}},
    {0x61, {"Sandslash", TYPE_GROUND, TYPE_GROUND, 28}},
    {0x62, {"Omanyte", TYPE_ROCK, TYPE_WATER, 138}},
    {0x63, {"Omastar", TYPE_ROCK, TYPE_WATER, 139}},
    {0x64, {"Jigglypuff", TYPE_NORMAL, TYPE_NORMAL, 39}},
    {0x65, {"Wigglytuff", TYPE_NORMAL, TYPE_NORMAL, 40}},
    {0x66, {"Eevee", TYPE_NORMAL, TYPE_NORMAL, 133}},
    {0x67, {"Flareon", TYPE_FIRE, TYPE_FIRE, 136}},
    {0x68, {"Jolteon", TYPE_ELECTRIC, TYPE_ELECTRIC, 135}},
    {0x69, {"Vaporeon", TYPE_WATER, TYPE_WATER, 134}},
    {0x6A, {"Machop", TYPE_FIGHTING, TYPE_FIGHTING, 66}},
    {0x6B, {"Zubat", TYPE_POISON, TYPE_FLYING, 41}},
    {0x6C, {"Ekans", TYPE_POISON, TYPE_POISON, 23}},
    {0x6D, {"Paras", TYPE_BUG, TYPE_GRASS, 46}},
    {0x6E, {"Poliwhirl", TYPE_WATER, TYPE_WATER, 61}},
    {0x6F, {"Poliwrath", TYPE_WATER, TYPE_FIGHTING, 62}},
    {0x70, {"Weedle", TYPE_BUG, TYPE_POISON, 13}},
    {0x71, {"Kakuna", TYPE_BUG, TYPE_POISON, 14}},
    {0x72, {"Beedrill", TYPE_BUG, TYPE_POISON, 15}},
    {0x73, {"MissingNo. (Houndoom)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x74, {"Dodrio", TYPE_NORMAL, TYPE_FLYING, 85}},
    {0x75, {"Primeape", TYPE_FIGHTING, TYPE_FIGHTING, 57}},
    {0x76, {"Dugtrio", TYPE_GROUND, TYPE_GROUND, 51}},
    {0x77, {"Venomoth", TYPE_BUG, TYPE_POISON, 49}},
    {0x78, {"Dewgong", TYPE_WATER, TYPE_ICE, 87}},
    {0x79, {"MissingNo. (Kingdra)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x7A, {"MissingNo. (Phanpy)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x7B, {"Caterpie", TYPE_BUG, TYPE_BUG, 10}},
    {0x7C, {"Metapod", TYPE_BUG, TYPE_BUG, 11}},
    {0x7D, {"Butterfree", TYPE_BUG, TYPE_FLYING, 12}},
    {0x7E, {"Machamp", TYPE_FIGHTING, TYPE_FIGHTING, 68}},
    {0x7F, {"MissingNo. (Donphan)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x80, {"Golduck", TYPE_WATER, TYPE_WATER, 55}},
    {0x81, {"Hypno", TYPE_PSYCHIC, TYPE_PSYCHIC, 97}},
    {0x82, {"Golbat", TYPE_POISON, TYPE_FLYING, 42}},
    {0x83, {"Mewtwo", TYPE_PSYCHIC, TYPE_PSYCHIC, 150}},
    {0x84, {"Snorlax", TYPE_NORMAL, TYPE_NORMAL, 143}},
    {0x85, {"Magikarp", TYPE_WATER, TYPE_WATER, 129}},
    {0x86, {"MissingNo. (Porygon2)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x87, {"MissingNo. (Stantler)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x88, {"Muk", TYPE_POISON, TYPE_POISON, 89}},
    {0x89, {"MissingNo. (Smeargle)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x8A, {"Kingler", TYPE_WATER, TYPE_WATER, 99}},
    {0x8B, {"Cloyster", TYPE_WATER, TYPE_ICE, 91}},
    {0x8C, {"MissingNo. (Tyrogue)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x8D, {"Electrode", TYPE_ELECTRIC, TYPE_ELECTRIC, 101}},
    {0x8E, {"Clefable", TYPE_NORMAL, TYPE_NORMAL, 36}},
    {0x8F, {"Weezing", TYPE_POISON, TYPE_POISON, 110}},
    {0x90, {"Persian", TYPE_NORMAL, TYPE_NORMAL, 53}},
    {0x91, {"Marowak", TYPE_GROUND, TYPE_GROUND, 105}},
    {0x92, {"MissingNo. (Hitmontop)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x93, {"Haunter", TYPE_GHOST, TYPE_POISON, 93}},
    {0x94, {"Abra", TYPE_PSYCHIC, TYPE_PSYCHIC, 63}},
    {0x95, {"Alakazam", TYPE_PSYCHIC, TYPE_PSYCHIC, 65}},
    {0x96, {"Pidgeotto", TYPE_NORMAL, TYPE_FLYING, 17}},
    {0x97, {"Pidgeot", TYPE_NORMAL, TYPE_FLYING, 18}},
    {0x98, {"Starmie", TYPE_WATER, TYPE_PSYCHIC, 121}},
    {0x99, {"Bulbasaur", TYPE_GRASS, TYPE_POISON, 1}},
    {0x9A, {"Venusaur", TYPE_GRASS, TYPE_POISON, 3}},
    {0x9B, {"Tentacruel", TYPE_WATER, TYPE_POISON, 73}},
    {0x9C, {"MissingNo. (Smoochum)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0x9D, {"Goldeen", TYPE_WATER, TYPE_WATER, 118}},
    {0x9E, {"Seaking", TYPE_WATER, TYPE_WATER, 119}},
    {0x9F, {"MissingNo. (Elekid)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0xA0, {"MissingNo. (Magby)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0xA1, {"MissingNo. (Miltank)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0xA2, {"MissingNo. (Blissey)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0xA3, {"Ponyta", TYPE_FIRE, TYPE_FIRE, 77}},
    {0xA4, {"Rapidash", TYPE_FIRE, TYPE_FIRE, 78}},
    {0xA5, {"Rattata", TYPE_NORMAL, TYPE_NORMAL, 19}},
    {0xA6, {"Raticate", TYPE_NORMAL, TYPE_NORMAL, 20}},
    {0xA7, {"Nidorino", TYPE_POISON, TYPE_POISON, 33}},
    {0xA8, {"Nidorina", TYPE_POISON, TYPE_POISON, 30}},
    {0xA9, {"Geodude", TYPE_ROCK, TYPE_GROUND, 74}},
    {0xAA, {"Porygon", TYPE_NORMAL, TYPE_NORMAL, 137}},
    {0xAB, {"Aerodactyl", TYPE_ROCK, TYPE_FLYING, 142}},
    {0xAC, {"MissingNo. (Raikou)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0xAD, {"Magnemite", TYPE_ELECTRIC, TYPE_ELECTRIC, 81}},
    {0xAE, {"MissingNo. (Entei)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0xAF, {"MissingNo. (Suicune)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0xB0, {"Charmander", TYPE_FIRE, TYPE_FIRE, 4}},
    {0xB1, {"Squirtle", TYPE_WATER, TYPE_WATER, 7}},
    {0xB2, {"Charmeleon", TYPE_FIRE, TYPE_FIRE, 5}},
    {0xB3, {"Wartortle", TYPE_WATER, TYPE_WATER, 8}},
    {0xB4, {"Charizard", TYPE_FIRE, TYPE_FLYING, 6}},
    {0xB5, {"MissingNo. (Larvitar)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0xB6, {"MissingNo. Kabutops Fossil (Pupitar)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0xB7, {"MissingNo. Aerodactyl Fossil (Tyranitar)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0xB8, {"MissingNo. Ghost (Lugia)", TYPE_BIRD, TYPE_NORMAL, 0}},
    {0xB9, {"Oddish", TYPE_GRASS, TYPE_POISON, 43}},
    {0xBA, {"Gloom", TYPE_GRASS, TYPE_POISON, 44}},
    {0xBB, {"Vileplume", TYPE_GRASS, TYPE_POISON, 45}},
    {0xBC, {"Bellsprout", TYPE_GRASS, TYPE_POISON, 69}},
    {0xBD, {"Weepinbell", TYPE_GRASS, TYPE_POISON, 70}},
    {0xBE, {"Victreebel", TYPE_GRASS, TYPE_POISON, 71}},
};

// ============================================================================
// Generation 2 Pokémon Table
// ============================================================================

static const std::unordered_map<uint8_t, PokemonInfo> GEN2_POKEMON = {
    {0x00, {"?????", TYPE_STEEL, TYPE_UNKNOWN, 0}},
    {0x01, {"Bulbasaur", TYPE_GRASS, TYPE_POISON, 1}},
    {0x02, {"Ivysaur", TYPE_GRASS, TYPE_POISON, 2}},
    {0x03, {"Venusaur", TYPE_GRASS, TYPE_POISON, 3}},
    {0x04, {"Charmander", TYPE_FIRE, TYPE_FIRE, 4}},
    {0x05, {"Charmeleon", TYPE_FIRE, TYPE_FIRE, 5}},
    {0x06, {"Charizard", TYPE_FIRE, TYPE_FLYING, 6}},
    {0x07, {"Squirtle", TYPE_WATER, TYPE_WATER, 7}},
    {0x08, {"Wartortle", TYPE_WATER, TYPE_WATER, 8}},
    {0x09, {"Blastoise", TYPE_WATER, TYPE_WATER, 9}},
    {0x0A, {"Caterpie", TYPE_BUG, TYPE_BUG, 10}},
    {0x0B, {"Metapod", TYPE_BUG, TYPE_BUG, 11}},
    {0x0C, {"Butterfree", TYPE_BUG, TYPE_FLYING, 12}},
    {0x0D, {"Weedle", TYPE_BUG, TYPE_POISON, 13}},
    {0x0E, {"Kakuna", TYPE_BUG, TYPE_POISON, 14}},
    {0x0F, {"Beedrill", TYPE_BUG, TYPE_POISON, 15}},
    {0x10, {"Pidgey", TYPE_NORMAL, TYPE_FLYING, 16}},
    {0x11, {"Pidgeotto", TYPE_NORMAL, TYPE_FLYING, 17}},
    {0x12, {"Pidgeot", TYPE_NORMAL, TYPE_FLYING, 18}},
    {0x13, {"Rattata", TYPE_NORMAL, TYPE_NORMAL, 19}},
    {0x14, {"Raticate", TYPE_NORMAL, TYPE_NORMAL, 20}},
    {0x15, {"Spearow", TYPE_NORMAL, TYPE_FLYING, 21}},
    {0x16, {"Fearow", TYPE_NORMAL, TYPE_FLYING, 22}},
    {0x17, {"Ekans", TYPE_POISON, TYPE_POISON, 23}},
    {0x18, {"Arbok", TYPE_POISON, TYPE_POISON, 24}},
    {0x19, {"Pikachu", TYPE_ELECTRIC, TYPE_ELECTRIC, 25}},
    {0x1A, {"Raichu", TYPE_ELECTRIC, TYPE_ELECTRIC, 26}},
    {0x1B, {"Sandshrew", TYPE_GROUND, TYPE_GROUND, 27}},
    {0x1C, {"Sandslash", TYPE_GROUND, TYPE_GROUND, 28}},
    {0x1D, {"Nidoran♀", TYPE_POISON, TYPE_POISON, 29}},
    {0x1E, {"Nidorina", TYPE_POISON, TYPE_POISON, 30}},
    {0x1F, {"Nidoqueen", TYPE_POISON, TYPE_GROUND, 31}},
    {0x20, {"Nidoran♂", TYPE_POISON, TYPE_POISON, 32}},
    {0x21, {"Nidorino", TYPE_POISON, TYPE_POISON, 33}},
    {0x22, {"Nidoking", TYPE_POISON, TYPE_GROUND, 34}},
    {0x23, {"Clefairy", TYPE_NORMAL, TYPE_NORMAL, 35}},
    {0x24, {"Clefable", TYPE_NORMAL, TYPE_NORMAL, 36}},
    {0x25, {"Vulpix", TYPE_FIRE, TYPE_FIRE, 37}},
    {0x26, {"Ninetales", TYPE_FIRE, TYPE_FIRE, 38}},
    {0x27, {"Jigglypuff", TYPE_NORMAL, TYPE_NORMAL, 39}},
    {0x28, {"Wigglytuff", TYPE_NORMAL, TYPE_NORMAL, 40}},
    {0x29, {"Zubat", TYPE_POISON, TYPE_FLYING, 41}},
    {0x2A, {"Golbat", TYPE_POISON, TYPE_FLYING, 42}},
    {0x2B, {"Oddish", TYPE_GRASS, TYPE_POISON, 43}},
    {0x2C, {"Gloom", TYPE_GRASS, TYPE_POISON, 44}},
    {0x2D, {"Vileplume", TYPE_GRASS, TYPE_POISON, 45}},
    {0x2E, {"Paras", TYPE_BUG, TYPE_GRASS, 46}},
    {0x2F, {"Parasect", TYPE_BUG, TYPE_GRASS, 47}},
    {0x30, {"Venonat", TYPE_BUG, TYPE_POISON, 48}},
    {0x31, {"Venomoth", TYPE_BUG, TYPE_POISON, 49}},
    {0x32, {"Diglett", TYPE_GROUND, TYPE_GROUND, 50}},
    {0x33, {"Dugtrio", TYPE_GROUND, TYPE_GROUND, 51}},
    {0x34, {"Meowth", TYPE_NORMAL, TYPE_NORMAL, 52}},
    {0x35, {"Persian", TYPE_NORMAL, TYPE_NORMAL, 53}},
    {0x36, {"Psyduck", TYPE_WATER, TYPE_WATER, 54}},
    {0x37, {"Golduck", TYPE_WATER, TYPE_WATER, 55}},
    {0x38, {"Mankey", TYPE_FIGHTING, TYPE_FIGHTING, 56}},
    {0x39, {"Primeape", TYPE_FIGHTING, TYPE_FIGHTING, 57}},
    {0x3A, {"Growlithe", TYPE_FIRE, TYPE_FIRE, 58}},
    {0x3B, {"Arcanine", TYPE_FIRE, TYPE_FIRE, 59}},
    {0x3C, {"Poliwag", TYPE_WATER, TYPE_WATER, 60}},
    {0x3D, {"Poliwhirl", TYPE_WATER, TYPE_WATER, 61}},
    {0x3E, {"Poliwrath", TYPE_WATER, TYPE_FIGHTING, 62}},
    {0x3F, {"Abra", TYPE_PSYCHIC, TYPE_PSYCHIC, 63}},
    {0x40, {"Kadabra", TYPE_PSYCHIC, TYPE_PSYCHIC, 64}},
    {0x41, {"Alakazam", TYPE_PSYCHIC, TYPE_PSYCHIC, 65}},
    {0x42, {"Machop", TYPE_FIGHTING, TYPE_FIGHTING, 66}},
    {0x43, {"Machoke", TYPE_FIGHTING, TYPE_FIGHTING, 67}},
    {0x44, {"Machamp", TYPE_FIGHTING, TYPE_FIGHTING, 68}},
    {0x45, {"Bellsprout", TYPE_GRASS, TYPE_POISON, 69}},
    {0x46, {"Weepinbell", TYPE_GRASS, TYPE_POISON, 70}},
    {0x47, {"Victreebel", TYPE_GRASS, TYPE_POISON, 71}},
    {0x48, {"Tentacool", TYPE_WATER, TYPE_POISON, 72}},
    {0x49, {"Tentacruel", TYPE_WATER, TYPE_POISON, 73}},
    {0x4A, {"Geodude", TYPE_ROCK, TYPE_GROUND, 74}},
    {0x4B, {"Graveler", TYPE_ROCK, TYPE_GROUND, 75}},
    {0x4C, {"Golem", TYPE_ROCK, TYPE_GROUND, 76}},
    {0x4D, {"Ponyta", TYPE_FIRE, TYPE_FIRE, 77}},
    {0x4E, {"Rapidash", TYPE_FIRE, TYPE_FIRE, 78}},
    {0x4F, {"Slowpoke", TYPE_WATER, TYPE_PSYCHIC, 79}},
    {0x50, {"Slowbro", TYPE_WATER, TYPE_PSYCHIC, 80}},
    {0x51, {"Magnemite", TYPE_ELECTRIC, TYPE_STEEL, 81}},
    {0x52, {"Magneton", TYPE_ELECTRIC, TYPE_STEEL, 82}},
    {0x53, {"Farfetch'd", TYPE_NORMAL, TYPE_FLYING, 83}},
    {0x54, {"Doduo", TYPE_NORMAL, TYPE_FLYING, 84}},
    {0x55, {"Dodrio", TYPE_NORMAL, TYPE_FLYING, 85}},
    {0x56, {"Seel", TYPE_WATER, TYPE_WATER, 86}},
    {0x57, {"Dewgong", TYPE_WATER, TYPE_ICE, 87}},
    {0x58, {"Grimer", TYPE_POISON, TYPE_POISON, 88}},
    {0x59, {"Muk", TYPE_POISON, TYPE_POISON, 89}},
    {0x5A, {"Shellder", TYPE_WATER, TYPE_WATER, 90}},
    {0x5B, {"Cloyster", TYPE_WATER, TYPE_ICE, 91}},
    {0x5C, {"Gastly", TYPE_GHOST, TYPE_POISON, 92}},
    {0x5D, {"Haunter", TYPE_GHOST, TYPE_POISON, 93}},
    {0x5E, {"Gengar", TYPE_GHOST, TYPE_POISON, 94}},
    {0x5F, {"Onix", TYPE_ROCK, TYPE_GROUND, 95}},
    {0x60, {"Drowzee", TYPE_PSYCHIC, TYPE_PSYCHIC, 96}},
    {0x61, {"Hypno", TYPE_PSYCHIC, TYPE_PSYCHIC, 97}},
    {0x62, {"Krabby", TYPE_WATER, TYPE_WATER, 98}},
    {0x63, {"Kingler", TYPE_WATER, TYPE_WATER, 99}},
    {0x64, {"Voltorb", TYPE_ELECTRIC, TYPE_ELECTRIC, 100}},
    {0x65, {"Electrode", TYPE_ELECTRIC, TYPE_ELECTRIC, 101}},
    {0x66, {"Exeggcute", TYPE_GRASS, TYPE_PSYCHIC, 102}},
    {0x67, {"Exeggutor", TYPE_GRASS, TYPE_PSYCHIC, 103}},
    {0x68, {"Cubone", TYPE_GROUND, TYPE_GROUND, 104}},
    {0x69, {"Marowak", TYPE_GROUND, TYPE_GROUND, 105}},
    {0x6A, {"Hitmonlee", TYPE_FIGHTING, TYPE_FIGHTING, 106}},
    {0x6B, {"Hitmonchan", TYPE_FIGHTING, TYPE_FIGHTING, 107}},
    {0x6C, {"Lickitung", TYPE_NORMAL, TYPE_NORMAL, 108}},
    {0x6D, {"Koffing", TYPE_POISON, TYPE_POISON, 109}},
    {0x6E, {"Weezing", TYPE_POISON, TYPE_POISON, 110}},
    {0x6F, {"Rhyhorn", TYPE_GROUND, TYPE_ROCK, 111}},
    {0x70, {"Rhydon", TYPE_GROUND, TYPE_ROCK, 112}},
    {0x71, {"Chansey", TYPE_NORMAL, TYPE_NORMAL, 113}},
    {0x72, {"Tangela", TYPE_GRASS, TYPE_GRASS, 114}},
    {0x73, {"Kangaskhan", TYPE_NORMAL, TYPE_NORMAL, 115}},
    {0x74, {"Horsea", TYPE_WATER, TYPE_WATER, 116}},
    {0x75, {"Seadra", TYPE_WATER, TYPE_WATER, 117}},
    {0x76, {"Goldeen", TYPE_WATER, TYPE_WATER, 118}},
    {0x77, {"Seaking", TYPE_WATER, TYPE_WATER, 119}},
    {0x78, {"Staryu", TYPE_WATER, TYPE_WATER, 120}},
    {0x79, {"Starmie", TYPE_WATER, TYPE_PSYCHIC, 121}},
    {0x7A, {"Mr. Mime", TYPE_PSYCHIC, TYPE_PSYCHIC, 122}},
    {0x7B, {"Scyther", TYPE_BUG, TYPE_FLYING, 123}},
    {0x7C, {"Jynx", TYPE_ICE, TYPE_PSYCHIC, 124}},
    {0x7D, {"Electabuzz", TYPE_ELECTRIC, TYPE_ELECTRIC, 125}},
    {0x7E, {"Magmar", TYPE_FIRE, TYPE_FIRE, 126}},
    {0x7F, {"Pinsir", TYPE_BUG, TYPE_BUG, 127}},
    {0x80, {"Tauros", TYPE_NORMAL, TYPE_NORMAL, 128}},
    {0x81, {"Magikarp", TYPE_WATER, TYPE_WATER, 129}},
    {0x82, {"Gyarados", TYPE_WATER, TYPE_FLYING, 130}},
    {0x83, {"Lapras", TYPE_WATER, TYPE_ICE, 131}},
    {0x84, {"Ditto", TYPE_NORMAL, TYPE_NORMAL, 132}},
    {0x85, {"Eevee", TYPE_NORMAL, TYPE_NORMAL, 133}},
    {0x86, {"Vaporeon", TYPE_WATER, TYPE_WATER, 134}},
    {0x87, {"Jolteon", TYPE_ELECTRIC, TYPE_ELECTRIC, 135}},
    {0x88, {"Flareon", TYPE_FIRE, TYPE_FIRE, 136}},
    {0x89, {"Porygon", TYPE_NORMAL, TYPE_NORMAL, 137}},
    {0x8A, {"Omanyte", TYPE_ROCK, TYPE_WATER, 138}},
    {0x8B, {"Omastar", TYPE_ROCK, TYPE_WATER, 139}},
    {0x8C, {"Kabuto", TYPE_ROCK, TYPE_WATER, 140}},
    {0x8D, {"Kabutops", TYPE_ROCK, TYPE_WATER, 141}},
    {0x8E, {"Aerodactyl", TYPE_ROCK, TYPE_FLYING, 142}},
    {0x8F, {"Snorlax", TYPE_NORMAL, TYPE_NORMAL, 143}},
    {0x90, {"Articuno", TYPE_ICE, TYPE_FLYING, 144}},
    {0x91, {"Zapdos", TYPE_ELECTRIC, TYPE_FLYING, 145}},
    {0x92, {"Moltres", TYPE_FIRE, TYPE_FLYING, 146}},
    {0x93, {"Dratini", TYPE_DRAGON, TYPE_DRAGON, 147}},
    {0x94, {"Dragonair", TYPE_DRAGON, TYPE_DRAGON, 148}},
    {0x95, {"Dragonite", TYPE_DRAGON, TYPE_FLYING, 149}},
    {0x96, {"Mewtwo", TYPE_PSYCHIC, TYPE_PSYCHIC, 150}},
    {0x97, {"Mew", TYPE_PSYCHIC, TYPE_PSYCHIC, 151}},
    {0x98, {"Chikorita", TYPE_GRASS, TYPE_GRASS, 152}},
    {0x99, {"Bayleef", TYPE_GRASS, TYPE_GRASS, 153}},
    {0x9A, {"Meganium", TYPE_GRASS, TYPE_GRASS, 154}},
    {0x9B, {"Cyndaquil", TYPE_FIRE, TYPE_FIRE, 155}},
    {0x9C, {"Quilava", TYPE_FIRE, TYPE_FIRE, 156}},
    {0x9D, {"Typhlosion", TYPE_FIRE, TYPE_FIRE, 157}},
    {0x9E, {"Totodile", TYPE_WATER, TYPE_WATER, 158}},
    {0x9F, {"Croconaw", TYPE_WATER, TYPE_WATER, 159}},
    {0xA0, {"Feraligatr", TYPE_WATER, TYPE_WATER, 160}},
    {0xA1, {"Sentret", TYPE_NORMAL, TYPE_NORMAL, 161}},
    {0xA2, {"Furret", TYPE_NORMAL, TYPE_NORMAL, 162}},
    {0xA3, {"Hoothoot", TYPE_NORMAL, TYPE_FLYING, 163}},
    {0xA4, {"Noctowl", TYPE_NORMAL, TYPE_FLYING, 164}},
    {0xA5, {"Ledyba", TYPE_BUG, TYPE_FLYING, 165}},
    {0xA6, {"Ledian", TYPE_BUG, TYPE_FLYING, 166}},
    {0xA7, {"Spinarak", TYPE_BUG, TYPE_POISON, 167}},
    {0xA8, {"Ariados", TYPE_BUG, TYPE_POISON, 168}},
    {0xA9, {"Crobat", TYPE_POISON, TYPE_FLYING, 169}},
    {0xAA, {"Chinchou", TYPE_WATER, TYPE_ELECTRIC, 170}},
    {0xAB, {"Lanturn", TYPE_WATER, TYPE_ELECTRIC, 171}},
    {0xAC, {"Pichu", TYPE_ELECTRIC, TYPE_ELECTRIC, 172}},
    {0xAD, {"Cleffa", TYPE_NORMAL, TYPE_NORMAL, 173}},
    {0xAE, {"Igglybuff", TYPE_NORMAL, TYPE_NORMAL, 174}},
    {0xAF, {"Togepi", TYPE_NORMAL, TYPE_NORMAL, 175}},
    {0xB0, {"Togetic", TYPE_NORMAL, TYPE_FLYING, 176}},
    {0xB1, {"Natu", TYPE_PSYCHIC, TYPE_FLYING, 177}},
    {0xB2, {"Xatu", TYPE_PSYCHIC, TYPE_FLYING, 178}},
    {0xB3, {"Mareep", TYPE_ELECTRIC, TYPE_ELECTRIC, 179}},
    {0xB4, {"Flaaffy", TYPE_ELECTRIC, TYPE_ELECTRIC, 180}},
    {0xB5, {"Ampharos", TYPE_ELECTRIC, TYPE_ELECTRIC, 181}},
    {0xB6, {"Bellossom", TYPE_GRASS, TYPE_GRASS, 182}},
    {0xB7, {"Marill", TYPE_WATER, TYPE_WATER, 183}},
    {0xB8, {"Azumarill", TYPE_WATER, TYPE_WATER, 184}},
    {0xB9, {"Sudowoodo", TYPE_ROCK, TYPE_ROCK, 185}},
    {0xBA, {"Politoed", TYPE_WATER, TYPE_WATER, 186}},
    {0xBB, {"Hoppip", TYPE_GRASS, TYPE_FLYING, 187}},
    {0xBC, {"Skiploom", TYPE_GRASS, TYPE_FLYING, 188}},
    {0xBD, {"Jumpluff", TYPE_GRASS, TYPE_FLYING, 189}},
    {0xBE, {"Aipom", TYPE_NORMAL, TYPE_NORMAL, 190}},
    {0xBF, {"Sunkern", TYPE_GRASS, TYPE_GRASS, 191}},
    {0xC0, {"Sunflora", TYPE_GRASS, TYPE_GRASS, 192}},
    {0xC1, {"Yanma", TYPE_BUG, TYPE_FLYING, 193}},
    {0xC2, {"Wooper", TYPE_WATER, TYPE_GROUND, 194}},
    {0xC3, {"Quagsire", TYPE_WATER, TYPE_GROUND, 195}},
    {0xC4, {"Espeon", TYPE_PSYCHIC, TYPE_PSYCHIC, 196}},
    {0xC5, {"Umbreon", TYPE_DARK, TYPE_DARK, 197}},
    {0xC6, {"Murkrow", TYPE_DARK, TYPE_FLYING, 198}},
    {0xC7, {"Slowking", TYPE_WATER, TYPE_PSYCHIC, 199}},
    {0xC8, {"Misdreavus", TYPE_GHOST, TYPE_GHOST, 200}},
    {0xC9, {"Unown", TYPE_PSYCHIC, TYPE_PSYCHIC, 201}},
    {0xCA, {"Wobbuffet", TYPE_PSYCHIC, TYPE_PSYCHIC, 202}},
    {0xCB, {"Girafarig", TYPE_NORMAL, TYPE_PSYCHIC, 203}},
    {0xCC, {"Pineco", TYPE_BUG, TYPE_BUG, 204}},
    {0xCD, {"Forretress", TYPE_BUG, TYPE_STEEL, 205}},
    {0xCE, {"Dunsparce", TYPE_NORMAL, TYPE_NORMAL, 206}},
    {0xCF, {"Gligar", TYPE_GROUND, TYPE_FLYING, 207}},
    {0xD0, {"Steelix", TYPE_STEEL, TYPE_GROUND, 208}},
    {0xD1, {"Snubbull", TYPE_NORMAL, TYPE_NORMAL, 209}},
    {0xD2, {"Granbull", TYPE_NORMAL, TYPE_NORMAL, 210}},
    {0xD3, {"Qwilfish", TYPE_WATER, TYPE_POISON, 211}},
    {0xD4, {"Scizor", TYPE_BUG, TYPE_STEEL, 212}},
    {0xD5, {"Shuckle", TYPE_BUG, TYPE_ROCK, 213}},
    {0xD6, {"Heracross", TYPE_BUG, TYPE_FIGHTING, 214}},
    {0xD7, {"Sneasel", TYPE_DARK, TYPE_ICE, 215}},
    {0xD8, {"Teddiursa", TYPE_NORMAL, TYPE_NORMAL, 216}},
    {0xD9, {"Ursaring", TYPE_NORMAL, TYPE_NORMAL, 217}},
    {0xDA, {"Slugma", TYPE_FIRE, TYPE_FIRE, 218}},
    {0xDB, {"Magcargo", TYPE_FIRE, TYPE_ROCK, 219}},
    {0xDC, {"Swinub", TYPE_ICE, TYPE_GROUND, 220}},
    {0xDD, {"Piloswine", TYPE_ICE, TYPE_GROUND, 221}},
    {0xDE, {"Corsola", TYPE_WATER, TYPE_ROCK, 222}},
    {0xDF, {"Remoraid", TYPE_WATER, TYPE_WATER, 223}},
    {0xE0, {"Octillery", TYPE_WATER, TYPE_WATER, 224}},
    {0xE1, {"Delibird", TYPE_ICE, TYPE_FLYING, 225}},
    {0xE2, {"Mantine", TYPE_WATER, TYPE_FLYING, 226}},
    {0xE3, {"Skarmory", TYPE_STEEL, TYPE_FLYING, 227}},
    {0xE4, {"Houndour", TYPE_DARK, TYPE_FIRE, 228}},
    {0xE5, {"Houndoom", TYPE_DARK, TYPE_FIRE, 229}},
    {0xE6, {"Kingdra", TYPE_WATER, TYPE_DRAGON, 230}},
    {0xE7, {"Phanpy", TYPE_GROUND, TYPE_GROUND, 231}},
    {0xE8, {"Donphan", TYPE_GROUND, TYPE_GROUND, 232}},
    {0xE9, {"Porygon2", TYPE_NORMAL, TYPE_NORMAL, 233}},
    {0xEA, {"Stantler", TYPE_NORMAL, TYPE_NORMAL, 234}},
    {0xEB, {"Smeargle", TYPE_NORMAL, TYPE_NORMAL, 235}},
    {0xEC, {"Tyrogue", TYPE_FIGHTING, TYPE_FIGHTING, 236}},
    {0xED, {"Hitmontop", TYPE_FIGHTING, TYPE_FIGHTING, 237}},
    {0xEE, {"Smoochum", TYPE_ICE, TYPE_PSYCHIC, 238}},
    {0xEF, {"Elekid", TYPE_ELECTRIC, TYPE_ELECTRIC, 239}},
    {0xF0, {"Magby", TYPE_FIRE, TYPE_FIRE, 240}},
    {0xF1, {"Miltank", TYPE_NORMAL, TYPE_NORMAL, 241}},
    {0xF2, {"Blissey", TYPE_NORMAL, TYPE_NORMAL, 242}},
    {0xF3, {"Raikou", TYPE_ELECTRIC, TYPE_ELECTRIC, 243}},
    {0xF4, {"Entei", TYPE_FIRE, TYPE_FIRE, 244}},
    {0xF5, {"Suicune", TYPE_WATER, TYPE_WATER, 245}},
    {0xF6, {"Larvitar", TYPE_ROCK, TYPE_GROUND, 246}},
    {0xF7, {"Pupitar", TYPE_ROCK, TYPE_GROUND, 247}},
    {0xF8, {"Tyranitar", TYPE_ROCK, TYPE_DARK, 248}},
    {0xF9, {"Lugia", TYPE_PSYCHIC, TYPE_FLYING, 249}},
    {0xFA, {"Ho-Oh", TYPE_FIRE, TYPE_FLYING, 250}},
    {0xFB, {"Celebi", TYPE_PSYCHIC, TYPE_GRASS, 251}},
    {0xFC, {"?????", TYPE_PSYCHIC, TYPE_UNKNOWN, 0}},
    {0xFD, {"Glitch Egg", TYPE_CURSE, TYPE_CURSE, 0}},
    {0xFE, {"?????", TYPE_NORMAL, TYPE_NORMAL, 0}},
    {0xFF, {"?????", TYPE_NORMAL, TYPE_NORMAL, 0}},
};

// ============================================================================
// Generation 3 Pokémon Table (indices per your provided list)
// Gen3 type ids are Gen3Type (0..17), NOT Gen1Type.
// Note: 0x001..0x0FB are looked up from GEN2 and converted on the fly.
// ============================================================================

static const std::unordered_map<uint16_t, PokemonInfo> GEN3_POKEMON = {
    {0x000, {"??????????", G3_NORMAL, G3_NORMAL, 0}},

    {0x01, {"Bulbasaur", TYPE_GRASS, TYPE_POISON, 1}},
    {0x02, {"Ivysaur", TYPE_GRASS, TYPE_POISON, 2}},
    {0x03, {"Venusaur", TYPE_GRASS, TYPE_POISON, 3}},
    {0x04, {"Charmander", TYPE_FIRE, TYPE_FIRE, 4}},
    {0x05, {"Charmeleon", TYPE_FIRE, TYPE_FIRE, 5}},
    {0x06, {"Charizard", TYPE_FIRE, TYPE_FLYING, 6}},
    {0x07, {"Squirtle", TYPE_WATER, TYPE_WATER, 7}},
    {0x08, {"Wartortle", TYPE_WATER, TYPE_WATER, 8}},
    {0x09, {"Blastoise", TYPE_WATER, TYPE_WATER, 9}},
    {0x0A, {"Caterpie", TYPE_BUG, TYPE_BUG, 10}},
    {0x0B, {"Metapod", TYPE_BUG, TYPE_BUG, 11}},
    {0x0C, {"Butterfree", TYPE_BUG, TYPE_FLYING, 12}},
    {0x0D, {"Weedle", TYPE_BUG, TYPE_POISON, 13}},
    {0x0E, {"Kakuna", TYPE_BUG, TYPE_POISON, 14}},
    {0x0F, {"Beedrill", TYPE_BUG, TYPE_POISON, 15}},
    {0x10, {"Pidgey", TYPE_NORMAL, TYPE_FLYING, 16}},
    {0x11, {"Pidgeotto", TYPE_NORMAL, TYPE_FLYING, 17}},
    {0x12, {"Pidgeot", TYPE_NORMAL, TYPE_FLYING, 18}},
    {0x13, {"Rattata", TYPE_NORMAL, TYPE_NORMAL, 19}},
    {0x14, {"Raticate", TYPE_NORMAL, TYPE_NORMAL, 20}},
    {0x15, {"Spearow", TYPE_NORMAL, TYPE_FLYING, 21}},
    {0x16, {"Fearow", TYPE_NORMAL, TYPE_FLYING, 22}},
    {0x17, {"Ekans", TYPE_POISON, TYPE_POISON, 23}},
    {0x18, {"Arbok", TYPE_POISON, TYPE_POISON, 24}},
    {0x19, {"Pikachu", TYPE_ELECTRIC, TYPE_ELECTRIC, 25}},
    {0x1A, {"Raichu", TYPE_ELECTRIC, TYPE_ELECTRIC, 26}},
    {0x1B, {"Sandshrew", TYPE_GROUND, TYPE_GROUND, 27}},
    {0x1C, {"Sandslash", TYPE_GROUND, TYPE_GROUND, 28}},
    {0x1D, {"Nidoran♀", TYPE_POISON, TYPE_POISON, 29}},
    {0x1E, {"Nidorina", TYPE_POISON, TYPE_POISON, 30}},
    {0x1F, {"Nidoqueen", TYPE_POISON, TYPE_GROUND, 31}},
    {0x20, {"Nidoran♂", TYPE_POISON, TYPE_POISON, 32}},
    {0x21, {"Nidorino", TYPE_POISON, TYPE_POISON, 33}},
    {0x22, {"Nidoking", TYPE_POISON, TYPE_GROUND, 34}},
    {0x23, {"Clefairy", TYPE_NORMAL, TYPE_NORMAL, 35}},
    {0x24, {"Clefable", TYPE_NORMAL, TYPE_NORMAL, 36}},
    {0x25, {"Vulpix", TYPE_FIRE, TYPE_FIRE, 37}},
    {0x26, {"Ninetales", TYPE_FIRE, TYPE_FIRE, 38}},
    {0x27, {"Jigglypuff", TYPE_NORMAL, TYPE_NORMAL, 39}},
    {0x28, {"Wigglytuff", TYPE_NORMAL, TYPE_NORMAL, 40}},
    {0x29, {"Zubat", TYPE_POISON, TYPE_FLYING, 41}},
    {0x2A, {"Golbat", TYPE_POISON, TYPE_FLYING, 42}},
    {0x2B, {"Oddish", TYPE_GRASS, TYPE_POISON, 43}},
    {0x2C, {"Gloom", TYPE_GRASS, TYPE_POISON, 44}},
    {0x2D, {"Vileplume", TYPE_GRASS, TYPE_POISON, 45}},
    {0x2E, {"Paras", TYPE_BUG, TYPE_GRASS, 46}},
    {0x2F, {"Parasect", TYPE_BUG, TYPE_GRASS, 47}},
    {0x30, {"Venonat", TYPE_BUG, TYPE_POISON, 48}},
    {0x31, {"Venomoth", TYPE_BUG, TYPE_POISON, 49}},
    {0x32, {"Diglett", TYPE_GROUND, TYPE_GROUND, 50}},
    {0x33, {"Dugtrio", TYPE_GROUND, TYPE_GROUND, 51}},
    {0x34, {"Meowth", TYPE_NORMAL, TYPE_NORMAL, 52}},
    {0x35, {"Persian", TYPE_NORMAL, TYPE_NORMAL, 53}},
    {0x36, {"Psyduck", TYPE_WATER, TYPE_WATER, 54}},
    {0x37, {"Golduck", TYPE_WATER, TYPE_WATER, 55}},
    {0x38, {"Mankey", TYPE_FIGHTING, TYPE_FIGHTING, 56}},
    {0x39, {"Primeape", TYPE_FIGHTING, TYPE_FIGHTING, 57}},
    {0x3A, {"Growlithe", TYPE_FIRE, TYPE_FIRE, 58}},
    {0x3B, {"Arcanine", TYPE_FIRE, TYPE_FIRE, 59}},
    {0x3C, {"Poliwag", TYPE_WATER, TYPE_WATER, 60}},
    {0x3D, {"Poliwhirl", TYPE_WATER, TYPE_WATER, 61}},
    {0x3E, {"Poliwrath", TYPE_WATER, TYPE_FIGHTING, 62}},
    {0x3F, {"Abra", TYPE_PSYCHIC, TYPE_PSYCHIC, 63}},
    {0x40, {"Kadabra", TYPE_PSYCHIC, TYPE_PSYCHIC, 64}},
    {0x41, {"Alakazam", TYPE_PSYCHIC, TYPE_PSYCHIC, 65}},
    {0x42, {"Machop", TYPE_FIGHTING, TYPE_FIGHTING, 66}},
    {0x43, {"Machoke", TYPE_FIGHTING, TYPE_FIGHTING, 67}},
    {0x44, {"Machamp", TYPE_FIGHTING, TYPE_FIGHTING, 68}},
    {0x45, {"Bellsprout", TYPE_GRASS, TYPE_POISON, 69}},
    {0x46, {"Weepinbell", TYPE_GRASS, TYPE_POISON, 70}},
    {0x47, {"Victreebel", TYPE_GRASS, TYPE_POISON, 71}},
    {0x48, {"Tentacool", TYPE_WATER, TYPE_POISON, 72}},
    {0x49, {"Tentacruel", TYPE_WATER, TYPE_POISON, 73}},
    {0x4A, {"Geodude", TYPE_ROCK, TYPE_GROUND, 74}},
    {0x4B, {"Graveler", TYPE_ROCK, TYPE_GROUND, 75}},
    {0x4C, {"Golem", TYPE_ROCK, TYPE_GROUND, 76}},
    {0x4D, {"Ponyta", TYPE_FIRE, TYPE_FIRE, 77}},
    {0x4E, {"Rapidash", TYPE_FIRE, TYPE_FIRE, 78}},
    {0x4F, {"Slowpoke", TYPE_WATER, TYPE_PSYCHIC, 79}},
    {0x50, {"Slowbro", TYPE_WATER, TYPE_PSYCHIC, 80}},
    {0x51, {"Magnemite", TYPE_ELECTRIC, TYPE_STEEL, 81}},
    {0x52, {"Magneton", TYPE_ELECTRIC, TYPE_STEEL, 82}},
    {0x53, {"Farfetch'd", TYPE_NORMAL, TYPE_FLYING, 83}},
    {0x54, {"Doduo", TYPE_NORMAL, TYPE_FLYING, 84}},
    {0x55, {"Dodrio", TYPE_NORMAL, TYPE_FLYING, 85}},
    {0x56, {"Seel", TYPE_WATER, TYPE_WATER, 86}},
    {0x57, {"Dewgong", TYPE_WATER, TYPE_ICE, 87}},
    {0x58, {"Grimer", TYPE_POISON, TYPE_POISON, 88}},
    {0x59, {"Muk", TYPE_POISON, TYPE_POISON, 89}},
    {0x5A, {"Shellder", TYPE_WATER, TYPE_WATER, 90}},
    {0x5B, {"Cloyster", TYPE_WATER, TYPE_ICE, 91}},
    {0x5C, {"Gastly", TYPE_GHOST, TYPE_POISON, 92}},
    {0x5D, {"Haunter", TYPE_GHOST, TYPE_POISON, 93}},
    {0x5E, {"Gengar", TYPE_GHOST, TYPE_POISON, 94}},
    {0x5F, {"Onix", TYPE_ROCK, TYPE_GROUND, 95}},
    {0x60, {"Drowzee", TYPE_PSYCHIC, TYPE_PSYCHIC, 96}},
    {0x61, {"Hypno", TYPE_PSYCHIC, TYPE_PSYCHIC, 97}},
    {0x62, {"Krabby", TYPE_WATER, TYPE_WATER, 98}},
    {0x63, {"Kingler", TYPE_WATER, TYPE_WATER, 99}},
    {0x64, {"Voltorb", TYPE_ELECTRIC, TYPE_ELECTRIC, 100}},
    {0x65, {"Electrode", TYPE_ELECTRIC, TYPE_ELECTRIC, 101}},
    {0x66, {"Exeggcute", TYPE_GRASS, TYPE_PSYCHIC, 102}},
    {0x67, {"Exeggutor", TYPE_GRASS, TYPE_PSYCHIC, 103}},
    {0x68, {"Cubone", TYPE_GROUND, TYPE_GROUND, 104}},
    {0x69, {"Marowak", TYPE_GROUND, TYPE_GROUND, 105}},
    {0x6A, {"Hitmonlee", TYPE_FIGHTING, TYPE_FIGHTING, 106}},
    {0x6B, {"Hitmonchan", TYPE_FIGHTING, TYPE_FIGHTING, 107}},
    {0x6C, {"Lickitung", TYPE_NORMAL, TYPE_NORMAL, 108}},
    {0x6D, {"Koffing", TYPE_POISON, TYPE_POISON, 109}},
    {0x6E, {"Weezing", TYPE_POISON, TYPE_POISON, 110}},
    {0x6F, {"Rhyhorn", TYPE_GROUND, TYPE_ROCK, 111}},
    {0x70, {"Rhydon", TYPE_GROUND, TYPE_ROCK, 112}},
    {0x71, {"Chansey", TYPE_NORMAL, TYPE_NORMAL, 113}},
    {0x72, {"Tangela", TYPE_GRASS, TYPE_GRASS, 114}},
    {0x73, {"Kangaskhan", TYPE_NORMAL, TYPE_NORMAL, 115}},
    {0x74, {"Horsea", TYPE_WATER, TYPE_WATER, 116}},
    {0x75, {"Seadra", TYPE_WATER, TYPE_WATER, 117}},
    {0x76, {"Goldeen", TYPE_WATER, TYPE_WATER, 118}},
    {0x77, {"Seaking", TYPE_WATER, TYPE_WATER, 119}},
    {0x78, {"Staryu", TYPE_WATER, TYPE_WATER, 120}},
    {0x79, {"Starmie", TYPE_WATER, TYPE_PSYCHIC, 121}},
    {0x7A, {"Mr. Mime", TYPE_PSYCHIC, TYPE_PSYCHIC, 122}},
    {0x7B, {"Scyther", TYPE_BUG, TYPE_FLYING, 123}},
    {0x7C, {"Jynx", TYPE_ICE, TYPE_PSYCHIC, 124}},
    {0x7D, {"Electabuzz", TYPE_ELECTRIC, TYPE_ELECTRIC, 125}},
    {0x7E, {"Magmar", TYPE_FIRE, TYPE_FIRE, 126}},
    {0x7F, {"Pinsir", TYPE_BUG, TYPE_BUG, 127}},
    {0x80, {"Tauros", TYPE_NORMAL, TYPE_NORMAL, 128}},
    {0x81, {"Magikarp", TYPE_WATER, TYPE_WATER, 129}},
    {0x82, {"Gyarados", TYPE_WATER, TYPE_FLYING, 130}},
    {0x83, {"Lapras", TYPE_WATER, TYPE_ICE, 131}},
    {0x84, {"Ditto", TYPE_NORMAL, TYPE_NORMAL, 132}},
    {0x85, {"Eevee", TYPE_NORMAL, TYPE_NORMAL, 133}},
    {0x86, {"Vaporeon", TYPE_WATER, TYPE_WATER, 134}},
    {0x87, {"Jolteon", TYPE_ELECTRIC, TYPE_ELECTRIC, 135}},
    {0x88, {"Flareon", TYPE_FIRE, TYPE_FIRE, 136}},
    {0x89, {"Porygon", TYPE_NORMAL, TYPE_NORMAL, 137}},
    {0x8A, {"Omanyte", TYPE_ROCK, TYPE_WATER, 138}},
    {0x8B, {"Omastar", TYPE_ROCK, TYPE_WATER, 139}},
    {0x8C, {"Kabuto", TYPE_ROCK, TYPE_WATER, 140}},
    {0x8D, {"Kabutops", TYPE_ROCK, TYPE_WATER, 141}},
    {0x8E, {"Aerodactyl", TYPE_ROCK, TYPE_FLYING, 142}},
    {0x8F, {"Snorlax", TYPE_NORMAL, TYPE_NORMAL, 143}},
    {0x90, {"Articuno", TYPE_ICE, TYPE_FLYING, 144}},
    {0x91, {"Zapdos", TYPE_ELECTRIC, TYPE_FLYING, 145}},
    {0x92, {"Moltres", TYPE_FIRE, TYPE_FLYING, 146}},
    {0x93, {"Dratini", TYPE_DRAGON, TYPE_DRAGON, 147}},
    {0x94, {"Dragonair", TYPE_DRAGON, TYPE_DRAGON, 148}},
    {0x95, {"Dragonite", TYPE_DRAGON, TYPE_FLYING, 149}},
    {0x96, {"Mewtwo", TYPE_PSYCHIC, TYPE_PSYCHIC, 150}},
    {0x97, {"Mew", TYPE_PSYCHIC, TYPE_PSYCHIC, 151}},
    {0x98, {"Chikorita", TYPE_GRASS, TYPE_GRASS, 152}},
    {0x99, {"Bayleef", TYPE_GRASS, TYPE_GRASS, 153}},
    {0x9A, {"Meganium", TYPE_GRASS, TYPE_GRASS, 154}},
    {0x9B, {"Cyndaquil", TYPE_FIRE, TYPE_FIRE, 155}},
    {0x9C, {"Quilava", TYPE_FIRE, TYPE_FIRE, 156}},
    {0x9D, {"Typhlosion", TYPE_FIRE, TYPE_FIRE, 157}},
    {0x9E, {"Totodile", TYPE_WATER, TYPE_WATER, 158}},
    {0x9F, {"Croconaw", TYPE_WATER, TYPE_WATER, 159}},
    {0xA0, {"Feraligatr", TYPE_WATER, TYPE_WATER, 160}},
    {0xA1, {"Sentret", TYPE_NORMAL, TYPE_NORMAL, 161}},
    {0xA2, {"Furret", TYPE_NORMAL, TYPE_NORMAL, 162}},
    {0xA3, {"Hoothoot", TYPE_NORMAL, TYPE_FLYING, 163}},
    {0xA4, {"Noctowl", TYPE_NORMAL, TYPE_FLYING, 164}},
    {0xA5, {"Ledyba", TYPE_BUG, TYPE_FLYING, 165}},
    {0xA6, {"Ledian", TYPE_BUG, TYPE_FLYING, 166}},
    {0xA7, {"Spinarak", TYPE_BUG, TYPE_POISON, 167}},
    {0xA8, {"Ariados", TYPE_BUG, TYPE_POISON, 168}},
    {0xA9, {"Crobat", TYPE_POISON, TYPE_FLYING, 169}},
    {0xAA, {"Chinchou", TYPE_WATER, TYPE_ELECTRIC, 170}},
    {0xAB, {"Lanturn", TYPE_WATER, TYPE_ELECTRIC, 171}},
    {0xAC, {"Pichu", TYPE_ELECTRIC, TYPE_ELECTRIC, 172}},
    {0xAD, {"Cleffa", TYPE_NORMAL, TYPE_NORMAL, 173}},
    {0xAE, {"Igglybuff", TYPE_NORMAL, TYPE_NORMAL, 174}},
    {0xAF, {"Togepi", TYPE_NORMAL, TYPE_NORMAL, 175}},
    {0xB0, {"Togetic", TYPE_NORMAL, TYPE_FLYING, 176}},
    {0xB1, {"Natu", TYPE_PSYCHIC, TYPE_FLYING, 177}},
    {0xB2, {"Xatu", TYPE_PSYCHIC, TYPE_FLYING, 178}},
    {0xB3, {"Mareep", TYPE_ELECTRIC, TYPE_ELECTRIC, 179}},
    {0xB4, {"Flaaffy", TYPE_ELECTRIC, TYPE_ELECTRIC, 180}},
    {0xB5, {"Ampharos", TYPE_ELECTRIC, TYPE_ELECTRIC, 181}},
    {0xB6, {"Bellossom", TYPE_GRASS, TYPE_GRASS, 182}},
    {0xB7, {"Marill", TYPE_WATER, TYPE_WATER, 183}},
    {0xB8, {"Azumarill", TYPE_WATER, TYPE_WATER, 184}},
    {0xB9, {"Sudowoodo", TYPE_ROCK, TYPE_ROCK, 185}},
    {0xBA, {"Politoed", TYPE_WATER, TYPE_WATER, 186}},
    {0xBB, {"Hoppip", TYPE_GRASS, TYPE_FLYING, 187}},
    {0xBC, {"Skiploom", TYPE_GRASS, TYPE_FLYING, 188}},
    {0xBD, {"Jumpluff", TYPE_GRASS, TYPE_FLYING, 189}},
    {0xBE, {"Aipom", TYPE_NORMAL, TYPE_NORMAL, 190}},
    {0xBF, {"Sunkern", TYPE_GRASS, TYPE_GRASS, 191}},
    {0xC0, {"Sunflora", TYPE_GRASS, TYPE_GRASS, 192}},
    {0xC1, {"Yanma", TYPE_BUG, TYPE_FLYING, 193}},
    {0xC2, {"Wooper", TYPE_WATER, TYPE_GROUND, 194}},
    {0xC3, {"Quagsire", TYPE_WATER, TYPE_GROUND, 195}},
    {0xC4, {"Espeon", TYPE_PSYCHIC, TYPE_PSYCHIC, 196}},
    {0xC5, {"Umbreon", TYPE_DARK, TYPE_DARK, 197}},
    {0xC6, {"Murkrow", TYPE_DARK, TYPE_FLYING, 198}},
    {0xC7, {"Slowking", TYPE_WATER, TYPE_PSYCHIC, 199}},
    {0xC8, {"Misdreavus", TYPE_GHOST, TYPE_GHOST, 200}},
    {0xC9, {"Unown", TYPE_PSYCHIC, TYPE_PSYCHIC, 201}},
    {0xCA, {"Wobbuffet", TYPE_PSYCHIC, TYPE_PSYCHIC, 202}},
    {0xCB, {"Girafarig", TYPE_NORMAL, TYPE_PSYCHIC, 203}},
    {0xCC, {"Pineco", TYPE_BUG, TYPE_BUG, 204}},
    {0xCD, {"Forretress", TYPE_BUG, TYPE_STEEL, 205}},
    {0xCE, {"Dunsparce", TYPE_NORMAL, TYPE_NORMAL, 206}},
    {0xCF, {"Gligar", TYPE_GROUND, TYPE_FLYING, 207}},
    {0xD0, {"Steelix", TYPE_STEEL, TYPE_GROUND, 208}},
    {0xD1, {"Snubbull", TYPE_NORMAL, TYPE_NORMAL, 209}},
    {0xD2, {"Granbull", TYPE_NORMAL, TYPE_NORMAL, 210}},
    {0xD3, {"Qwilfish", TYPE_WATER, TYPE_POISON, 211}},
    {0xD4, {"Scizor", TYPE_BUG, TYPE_STEEL, 212}},
    {0xD5, {"Shuckle", TYPE_BUG, TYPE_ROCK, 213}},
    {0xD6, {"Heracross", TYPE_BUG, TYPE_FIGHTING, 214}},
    {0xD7, {"Sneasel", TYPE_DARK, TYPE_ICE, 215}},
    {0xD8, {"Teddiursa", TYPE_NORMAL, TYPE_NORMAL, 216}},
    {0xD9, {"Ursaring", TYPE_NORMAL, TYPE_NORMAL, 217}},
    {0xDA, {"Slugma", TYPE_FIRE, TYPE_FIRE, 218}},
    {0xDB, {"Magcargo", TYPE_FIRE, TYPE_ROCK, 219}},
    {0xDC, {"Swinub", TYPE_ICE, TYPE_GROUND, 220}},
    {0xDD, {"Piloswine", TYPE_ICE, TYPE_GROUND, 221}},
    {0xDE, {"Corsola", TYPE_WATER, TYPE_ROCK, 222}},
    {0xDF, {"Remoraid", TYPE_WATER, TYPE_WATER, 223}},
    {0xE0, {"Octillery", TYPE_WATER, TYPE_WATER, 224}},
    {0xE1, {"Delibird", TYPE_ICE, TYPE_FLYING, 225}},
    {0xE2, {"Mantine", TYPE_WATER, TYPE_FLYING, 226}},
    {0xE3, {"Skarmory", TYPE_STEEL, TYPE_FLYING, 227}},
    {0xE4, {"Houndour", TYPE_DARK, TYPE_FIRE, 228}},
    {0xE5, {"Houndoom", TYPE_DARK, TYPE_FIRE, 229}},
    {0xE6, {"Kingdra", TYPE_WATER, TYPE_DRAGON, 230}},
    {0xE7, {"Phanpy", TYPE_GROUND, TYPE_GROUND, 231}},
    {0xE8, {"Donphan", TYPE_GROUND, TYPE_GROUND, 232}},
    {0xE9, {"Porygon2", TYPE_NORMAL, TYPE_NORMAL, 233}},
    {0xEA, {"Stantler", TYPE_NORMAL, TYPE_NORMAL, 234}},
    {0xEB, {"Smeargle", TYPE_NORMAL, TYPE_NORMAL, 235}},
    {0xEC, {"Tyrogue", TYPE_FIGHTING, TYPE_FIGHTING, 236}},
    {0xED, {"Hitmontop", TYPE_FIGHTING, TYPE_FIGHTING, 237}},
    {0xEE, {"Smoochum", TYPE_ICE, TYPE_PSYCHIC, 238}},
    {0xEF, {"Elekid", TYPE_ELECTRIC, TYPE_ELECTRIC, 239}},
    {0xF0, {"Magby", TYPE_FIRE, TYPE_FIRE, 240}},
    {0xF1, {"Miltank", TYPE_NORMAL, TYPE_NORMAL, 241}},
    {0xF2, {"Blissey", TYPE_NORMAL, TYPE_NORMAL, 242}},
    {0xF3, {"Raikou", TYPE_ELECTRIC, TYPE_ELECTRIC, 243}},
    {0xF4, {"Entei", TYPE_FIRE, TYPE_FIRE, 244}},
    {0xF5, {"Suicune", TYPE_WATER, TYPE_WATER, 245}},
    {0xF6, {"Larvitar", TYPE_ROCK, TYPE_GROUND, 246}},
    {0xF7, {"Pupitar", TYPE_ROCK, TYPE_GROUND, 247}},
    {0xF8, {"Tyranitar", TYPE_ROCK, TYPE_DARK, 248}},
    {0xF9, {"Lugia", TYPE_PSYCHIC, TYPE_FLYING, 249}},
    {0xFA, {"Ho-Oh", TYPE_FIRE, TYPE_FLYING, 250}},
    {0xFB, {"Celebi", TYPE_PSYCHIC, TYPE_GRASS, 251}},

    // Placeholders (Normal)
    {0x0FC, {"?", G3_NORMAL, G3_NORMAL, 0}}, {0x0FD, {"?", G3_NORMAL, G3_NORMAL, 0}},
    {0x0FE, {"?", G3_NORMAL, G3_NORMAL, 0}}, {0x0FF, {"?", G3_NORMAL, G3_NORMAL, 0}},
    {0x100, {"?", G3_NORMAL, G3_NORMAL, 0}}, {0x101, {"?", G3_NORMAL, G3_NORMAL, 0}},
    {0x102, {"?", G3_NORMAL, G3_NORMAL, 0}}, {0x103, {"?", G3_NORMAL, G3_NORMAL, 0}},
    {0x104, {"?", G3_NORMAL, G3_NORMAL, 0}}, {0x105, {"?", G3_NORMAL, G3_NORMAL, 0}},
    {0x106, {"?", G3_NORMAL, G3_NORMAL, 0}}, {0x107, {"?", G3_NORMAL, G3_NORMAL, 0}},
    {0x108, {"?", G3_NORMAL, G3_NORMAL, 0}}, {0x109, {"?", G3_NORMAL, G3_NORMAL, 0}},
    {0x10A, {"?", G3_NORMAL, G3_NORMAL, 0}}, {0x10B, {"?", G3_NORMAL, G3_NORMAL, 0}},
    {0x10C, {"?", G3_NORMAL, G3_NORMAL, 0}}, {0x10D, {"?", G3_NORMAL, G3_NORMAL, 0}},
    {0x10E, {"?", G3_NORMAL, G3_NORMAL, 0}}, {0x10F, {"?", G3_NORMAL, G3_NORMAL, 0}},
    {0x110, {"?", G3_NORMAL, G3_NORMAL, 0}}, {0x111, {"?", G3_NORMAL, G3_NORMAL, 0}},
    {0x112, {"?", G3_NORMAL, G3_NORMAL, 0}}, {0x113, {"?", G3_NORMAL, G3_NORMAL, 0}},
    {0x114, {"?", G3_NORMAL, G3_NORMAL, 0}},

    // Gen 3 block (0x115..0x19B)
    {0x115, {"Treecko", G3_GRASS, G3_GRASS, 252}},
    {0x116, {"Grovyle", G3_GRASS, G3_GRASS, 253}},
    {0x117, {"Sceptile", G3_GRASS, G3_GRASS, 254}},
    {0x118, {"Torchic", G3_FIRE, G3_FIRE, 255}},
    {0x119, {"Combusken", G3_FIRE, G3_FIGHTING, 256}},
    {0x11A, {"Blaziken", G3_FIRE, G3_FIGHTING, 257}},
    {0x11B, {"Mudkip", G3_WATER, G3_WATER, 258}},
    {0x11C, {"Marshtomp", G3_WATER, G3_GROUND, 259}},
    {0x11D, {"Swampert", G3_WATER, G3_GROUND, 260}},
    {0x11E, {"Poochyena", G3_DARK, G3_DARK, 261}},
    {0x11F, {"Mightyena", G3_DARK, G3_DARK, 262}},
    {0x120, {"Zigzagoon", G3_NORMAL, G3_NORMAL, 263}},
    {0x121, {"Linoone", G3_NORMAL, G3_NORMAL, 264}},
    {0x122, {"Wurmple", G3_BUG, G3_BUG, 265}},
    {0x123, {"Silcoon", G3_BUG, G3_BUG, 266}},
    {0x124, {"Beautifly", G3_BUG, G3_FLYING, 267}},
    {0x125, {"Cascoon", G3_BUG, G3_BUG, 268}},
    {0x126, {"Dustox", G3_BUG, G3_POISON, 269}},
    {0x127, {"Lotad", G3_WATER, G3_GRASS, 270}},
    {0x128, {"Lombre", G3_WATER, G3_GRASS, 271}},
    {0x129, {"Ludicolo", G3_WATER, G3_GRASS, 272}},
    {0x12A, {"Seedot", G3_GRASS, G3_GRASS, 273}},
    {0x12B, {"Nuzleaf", G3_GRASS, G3_DARK, 274}},
    {0x12C, {"Shiftry", G3_GRASS, G3_DARK, 275}},
    {0x12D, {"Nincada", G3_BUG, G3_GROUND, 290}},
    {0x12E, {"Ninjask", G3_BUG, G3_FLYING, 291}},
    {0x12F, {"Shedinja", G3_BUG, G3_GHOST, 292}},
    {0x130, {"Taillow", G3_NORMAL, G3_FLYING, 276}},
    {0x131, {"Swellow", G3_NORMAL, G3_FLYING, 277}},
    {0x132, {"Shroomish", G3_GRASS, G3_GRASS, 285}},
    {0x133, {"Breloom", G3_GRASS, G3_FIGHTING, 286}},
    {0x134, {"Spinda", G3_NORMAL, G3_NORMAL, 327}},
    {0x135, {"Wingull", G3_WATER, G3_FLYING, 278}},
    {0x136, {"Pelipper", G3_WATER, G3_FLYING, 279}},
    {0x137, {"Surskit", G3_BUG, G3_WATER, 283}},
    {0x138, {"Masquerain", G3_BUG, G3_FLYING, 284}},
    {0x139, {"Wailmer", G3_WATER, G3_WATER, 320}},
    {0x13A, {"Wailord", G3_WATER, G3_WATER, 321}},
    {0x13B, {"Skitty", G3_NORMAL, G3_NORMAL, 300}},
    {0x13C, {"Delcatty", G3_NORMAL, G3_NORMAL, 301}},
    {0x13D, {"Kecleon", G3_NORMAL, G3_NORMAL, 352}},
    {0x13E, {"Baltoy", G3_GROUND, G3_PSYCHIC, 343}},
    {0x13F, {"Claydol", G3_GROUND, G3_PSYCHIC, 344}},
    {0x140, {"Nosepass", G3_ROCK, G3_ROCK, 299}},
    {0x141, {"Torkoal", G3_FIRE, G3_FIRE, 324}},
    {0x142, {"Sableye", G3_DARK, G3_GHOST, 302}},
    {0x143, {"Barboach", G3_WATER, G3_GROUND, 339}},
    {0x144, {"Whiscash", G3_WATER, G3_GROUND, 340}},
    {0x145, {"Luvdisc", G3_WATER, G3_WATER, 370}},
    {0x146, {"Corphish", G3_WATER, G3_WATER, 341}},
    {0x147, {"Crawdaunt", G3_WATER, G3_DARK, 342}},
    {0x148, {"Feebas", G3_WATER, G3_WATER, 349}},
    {0x149, {"Milotic", G3_WATER, G3_WATER, 350}},
    {0x14A, {"Carvanha", G3_WATER, G3_DARK, 318}},
    {0x14B, {"Sharpedo", G3_WATER, G3_DARK, 319}},
    {0x14C, {"Trapinch", G3_GROUND, G3_GROUND, 328}},
    {0x14D, {"Vibrava", G3_GROUND, G3_DRAGON, 329}},
    {0x14E, {"Flygon", G3_GROUND, G3_DRAGON, 330}},
    {0x14F, {"Makuhita", G3_FIGHTING, G3_FIGHTING, 296}},
    {0x150, {"Hariyama", G3_FIGHTING, G3_FIGHTING, 297}},
    {0x151, {"Electrike", G3_ELECTRIC, G3_ELECTRIC, 309}},
    {0x152, {"Manectric", G3_ELECTRIC, G3_ELECTRIC, 310}},
    {0x153, {"Numel", G3_FIRE, G3_GROUND, 322}},
    {0x154, {"Camerupt", G3_FIRE, G3_GROUND, 323}},
    {0x155, {"Spheal", G3_ICE, G3_WATER, 363}},
    {0x156, {"Sealeo", G3_ICE, G3_WATER, 364}},
    {0x157, {"Walrein", G3_ICE, G3_WATER, 365}},
    {0x158, {"Cacnea", G3_GRASS, G3_GRASS, 331}},
    {0x159, {"Cacturne", G3_GRASS, G3_DARK, 332}},
    {0x15A, {"Snorunt", G3_ICE, G3_ICE, 361}},
    {0x15B, {"Glalie", G3_ICE, G3_ICE, 362}},
    {0x15C, {"Lunatone", G3_ROCK, G3_PSYCHIC, 337}},
    {0x15D, {"Solrock", G3_ROCK, G3_PSYCHIC, 338}},
    {0x15E, {"Azurill", G3_NORMAL, G3_NORMAL, 298}},
    {0x15F, {"Spoink", G3_PSYCHIC, G3_PSYCHIC, 325}},
    {0x160, {"Grumpig", G3_PSYCHIC, G3_PSYCHIC, 326}},
    {0x161, {"Plusle", G3_ELECTRIC, G3_ELECTRIC, 311}},
    {0x162, {"Minun", G3_ELECTRIC, G3_ELECTRIC, 312}},
    {0x163, {"Mawile", G3_STEEL, G3_STEEL, 303}},
    {0x164, {"Meditite", G3_FIGHTING, G3_PSYCHIC, 307}},
    {0x165, {"Medicham", G3_FIGHTING, G3_PSYCHIC, 308}},
    {0x166, {"Swablu", G3_NORMAL, G3_FLYING, 333}},
    {0x167, {"Altaria", G3_DRAGON, G3_FLYING, 334}},
    {0x168, {"Wynaut", G3_PSYCHIC, G3_PSYCHIC, 360}},
    {0x169, {"Duskull", G3_GHOST, G3_GHOST, 355}},
    {0x16A, {"Dusclops", G3_GHOST, G3_GHOST, 356}},
    {0x16B, {"Roselia", G3_GRASS, G3_POISON, 315}},
    {0x16C, {"Slakoth", G3_NORMAL, G3_NORMAL, 287}},
    {0x16D, {"Vigoroth", G3_NORMAL, G3_NORMAL, 288}},
    {0x16E, {"Slaking", G3_NORMAL, G3_NORMAL, 289}},
    {0x16F, {"Gulpin", G3_POISON, G3_POISON, 316}},
    {0x170, {"Swalot", G3_POISON, G3_POISON, 317}},
    {0x171, {"Tropius", G3_GRASS, G3_FLYING, 357}},
    {0x172, {"Whismur", G3_NORMAL, G3_NORMAL, 293}},
    {0x173, {"Loudred", G3_NORMAL, G3_NORMAL, 294}},
    {0x174, {"Exploud", G3_NORMAL, G3_NORMAL, 295}},
    {0x175, {"Clamperl", G3_WATER, G3_WATER, 366}},
    {0x176, {"Huntail", G3_WATER, G3_WATER, 367}},
    {0x177, {"Gorebyss", G3_WATER, G3_WATER, 368}},
    {0x178, {"Absol", G3_DARK, G3_DARK, 359}},
    {0x179, {"Shuppet", G3_GHOST, G3_GHOST, 353}},
    {0x17A, {"Banette", G3_GHOST, G3_GHOST, 354}},
    {0x17B, {"Seviper", G3_POISON, G3_POISON, 336}},
    {0x17C, {"Zangoose", G3_NORMAL, G3_NORMAL, 335}},
    {0x17D, {"Relicanth", G3_ROCK, G3_WATER, 369}},
    {0x17E, {"Aron", G3_STEEL, G3_ROCK, 304}},
    {0x17F, {"Lairon", G3_STEEL, G3_ROCK, 305}},
    {0x180, {"Aggron", G3_STEEL, G3_ROCK, 306}},
    {0x181, {"Castform", G3_NORMAL, G3_NORMAL, 351}},
    {0x182, {"Volbeat", G3_BUG, G3_BUG, 313}},
    {0x183, {"Illumise", G3_BUG, G3_BUG, 314}},
    {0x184, {"Lileep", G3_ROCK, G3_GRASS, 345}},
    {0x185, {"Cradily", G3_ROCK, G3_GRASS, 346}},
    {0x186, {"Anorith", G3_ROCK, G3_BUG, 347}},
    {0x187, {"Armaldo", G3_ROCK, G3_BUG, 348}},
    {0x188, {"Ralts", G3_PSYCHIC, G3_PSYCHIC, 280}},
    {0x189, {"Kirlia", G3_PSYCHIC, G3_PSYCHIC, 281}},
    {0x18A, {"Gardevoir", G3_PSYCHIC, G3_PSYCHIC, 282}},
    {0x18B, {"Bagon", G3_DRAGON, G3_DRAGON, 371}},
    {0x18C, {"Shelgon", G3_DRAGON, G3_DRAGON, 372}},
    {0x18D, {"Salamence", G3_DRAGON, G3_FLYING, 373}},
    {0x18E, {"Beldum", G3_STEEL, G3_PSYCHIC, 374}},
    {0x18F, {"Metang", G3_STEEL, G3_PSYCHIC, 375}},
    {0x190, {"Metagross", G3_STEEL, G3_PSYCHIC, 376}},
    {0x191, {"Regirock", G3_ROCK, G3_ROCK, 377}},
    {0x192, {"Regice", G3_ICE, G3_ICE, 378}},
    {0x193, {"Registeel", G3_STEEL, G3_STEEL, 379}},
    {0x194, {"Kyogre", G3_WATER, G3_WATER, 382}},
    {0x195, {"Groudon", G3_GROUND, G3_GROUND, 383}},
    {0x196, {"Rayquaza", G3_DRAGON, G3_FLYING, 384}},
    {0x197, {"Latias", G3_DRAGON, G3_PSYCHIC, 380}},
    {0x198, {"Latios", G3_DRAGON, G3_PSYCHIC, 381}},
    {0x199, {"Jirachi", G3_STEEL, G3_PSYCHIC, 385}},
    {0x19A, {"Deoxys", G3_PSYCHIC, G3_PSYCHIC, 386}},
    {0x19B, {"Chimecho", G3_PSYCHIC, G3_PSYCHIC, 358}},

    // Pokémon Egg (???)
    {0x19C, {"Pokémon Egg", G3_MYSTERY, G3_MYSTERY, 0}},

    // Unown variants (B.. ? etc) — all Psychic in your table
    {0x19D, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x19E, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x19F, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1A0, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1A1, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1A2, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1A3, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1A4, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1A5, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1A6, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1A7, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1A8, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1A9, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1AA, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1AB, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1AC, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1AD, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1AE, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1AF, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1B0, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1B1, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1B2, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1B3, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1B4, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1B5, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1B6, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
    {0x1B7, {"Unown", G3_PSYCHIC, G3_PSYCHIC, 201}},
};

// ============================================================================
// Utility functions
// ============================================================================

// Map Gen 1/2 type ids to Gen 3 type ids (0..17)
inline uint8_t mapGen12TypeToGen3(uint8_t t) {
    switch (t) {
        case TYPE_NORMAL:   return G3_NORMAL;
        case TYPE_FIGHTING: return G3_FIGHTING;
        case TYPE_FLYING:   return G3_FLYING;
        case TYPE_POISON:   return G3_POISON;
        case TYPE_GROUND:   return G3_GROUND;
        case TYPE_ROCK:     return G3_ROCK;
        case TYPE_BUG:      return G3_BUG;
        case TYPE_GHOST:    return G3_GHOST;
        case TYPE_STEEL:    return G3_STEEL;
        case TYPE_FIRE:     return G3_FIRE;
        case TYPE_WATER:    return G3_WATER;
        case TYPE_GRASS:    return G3_GRASS;
        case TYPE_ELECTRIC: return G3_ELECTRIC;
        case TYPE_PSYCHIC:  return G3_PSYCHIC;
        case TYPE_ICE:      return G3_ICE;
        case TYPE_DRAGON:   return G3_DRAGON;
        case TYPE_DARK:     return G3_DARK;
        case TYPE_CURSE:    return G3_MYSTERY;
        default:            return G3_UNKNOWN; // includes TYPE_BIRD / TYPE_UNKNOWN etc.
    }
}

// Wide-index version (supports Gen 3 indices > 0xFF)
inline const PokemonInfo* getPokemonInfo(uint16_t index, int generation) {
    switch (generation) {
        case 1: {
            if (index > 0xFF) return nullptr;
            auto it = GEN1_POKEMON.find(static_cast<uint8_t>(index));
            return (it != GEN1_POKEMON.end()) ? &it->second : nullptr;
        }
        case 2: {
            if (index > 0xFF) return nullptr;
            auto it = GEN2_POKEMON.find(static_cast<uint8_t>(index));
            return (it != GEN2_POKEMON.end()) ? &it->second : nullptr;
        }
        case 3: {
            // First check Gen3 explicit table (overrides + all >0xFB entries)
            auto it3 = GEN3_POKEMON.find(index);
            if (it3 != GEN3_POKEMON.end()) return &it3->second;

            // For 0x001..0x0FB, Gen3 names match Gen2, but types must be remapped.
            if (index >= 0x001 && index <= 0x0FB) {
                auto it2 = GEN2_POKEMON.find(static_cast<uint8_t>(index));
                if (it2 == GEN2_POKEMON.end()) return nullptr;

                static thread_local PokemonInfo converted;
                converted.name  = it2->second.name;
                converted.type1 = mapGen12TypeToGen3(it2->second.type1);
                converted.type2 = mapGen12TypeToGen3(it2->second.type2);
                converted.nationalDexNum = it2->second.nationalDexNum;
                return &converted;
            }

            return nullptr;
        }
        default:
            return nullptr;
    }
}

// Backward-compatible original signature
inline const PokemonInfo* getPokemonInfo(uint8_t index, int generation) {
    return getPokemonInfo(static_cast<uint16_t>(index), generation);
}

// Name helpers
inline const char* getPokemonName(uint16_t index, int generation) {
    const PokemonInfo* info = getPokemonInfo(index, generation);
    return info ? info->name : nullptr;
}

inline const char* getPokemonName(uint8_t index, int generation) {
    return getPokemonName(static_cast<uint16_t>(index), generation);
}

// Type helpers
inline uint8_t getPokemonType1(uint16_t index, int generation) {
    const PokemonInfo* info = getPokemonInfo(index, generation);
    return info ? info->type1 : TYPE_UNKNOWN;
}
inline uint8_t getPokemonType1(uint8_t index, int generation) {
    return getPokemonType1(static_cast<uint16_t>(index), generation);
}

inline uint8_t getPokemonType2(uint16_t index, int generation) {
    const PokemonInfo* info = getPokemonInfo(index, generation);
    return info ? info->type2 : TYPE_UNKNOWN;
}
inline uint8_t getPokemonType2(uint8_t index, int generation) {
    return getPokemonType2(static_cast<uint16_t>(index), generation);
}

// Combined types (type1 in upper byte, type2 in lower byte, or 0xFFFF if not found)
inline uint16_t getPokemonTypes(uint16_t index, int generation) {
    uint8_t type1 = getPokemonType1(index, generation);
    uint8_t type2 = getPokemonType2(index, generation);

    if (type1 == TYPE_UNKNOWN && type2 == TYPE_UNKNOWN) return 0xFFFF;
    return (static_cast<uint16_t>(type1) << 8) | type2;
}
inline uint16_t getPokemonTypes(uint8_t index, int generation) {
    return getPokemonTypes(static_cast<uint16_t>(index), generation);
}

// ============================================================================
// Gen 1-specific functions
// ============================================================================

inline const PokemonInfo* getGen1PokemonInfo(uint8_t index) { return getPokemonInfo(index, 1); }
inline const char* getGen1PokemonName(uint8_t index) { return getPokemonName(index, 1); }
inline uint8_t getGen1PokemonType1(uint8_t index) { return getPokemonType1(index, 1); }
inline uint8_t getGen1PokemonType2(uint8_t index) { return getPokemonType2(index, 1); }

// ============================================================================
// Gen 2-specific functions
// ============================================================================

inline const PokemonInfo* getGen2PokemonInfo(uint8_t index) { return getPokemonInfo(index, 2); }
inline const char* getGen2PokemonName(uint8_t index) { return getPokemonName(index, 2); }
inline uint8_t getGen2PokemonType1(uint8_t index) { return getPokemonType1(index, 2); }
inline uint8_t getGen2PokemonType2(uint8_t index) { return getPokemonType2(index, 2); }

// ============================================================================
// Gen 3-specific functions
// ============================================================================

inline const PokemonInfo* getGen3PokemonInfo(uint16_t index) { return getPokemonInfo(index, 3); }
inline const char* getGen3PokemonName(uint16_t index) { return getPokemonName(index, 3); }
inline uint8_t getGen3PokemonType1(uint16_t index) { return getPokemonType1(index, 3); }
inline uint8_t getGen3PokemonType2(uint16_t index) { return getPokemonType2(index, 3); }
inline uint16_t getGen3PokemonTypes(uint16_t index) { return getPokemonTypes(index, 3); }

inline bool isGen3UnownVariant(uint16_t index) {
    return index >= 0x19D && index <= 0x1B7;
}

} // namespace PokemonIndex

#endif // POKEMON_INDEX_ENG_H
